server:
  port: 8082 # Puerto distinto para las órdenes

spring:
  datasource:
    url: jdbc:h2:mem:workordersdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true