server:
  port: 8081

spring:
  application:
    name: digitalfix-workorders
  datasource:
    url: jdbc:h2:mem:workordersdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: health,info

info:
  app:
    name: digitalfix-workorders
    version: 0.0.1-SNAPSHOT

---
spring:
  config:
    activate:
      on-profile: oracle
  datasource:
    url: ${ORACLE_URL:jdbc:oracle:thin:@localhost:1521/XE}
    username: ${ORACLE_USER:digitalfix}
    password: ${ORACLE_PASSWORD:digitalfix}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
